#! /bin/sh

NAME=stm
DAEMON=/usr/bin/python
DAEMON_OPTS="-- /home/kate/ServeToMe/stm.py"
PIDFILE=/var/run/$NAME.pid
DESC="ServeToMe daemon"
USER="kate"

set -e

case "$1" in
  start)
	echo -n "Starting $DESC: "
	start-stop-daemon --start --background --chuid $USER --pidfile $PIDFILE --m --exec $DAEMON -- $DAEMON_OPTS
	echo "$NAME."
	;;
  stop)
	echo -n "Stopping $DESC: "
	start-stop-daemon --stop --pidfile $PIDFILE
	echo "$NAME."
	;;
  restart)
	echo -n "Stopping $DESC: "
	start-stop-daemon --stop --pidfile $PIDFILE
	sleep 1
	echo -n "Restarting $DESC: "
	start-stop-daemon --start --background --chuid $USER --pidfile $PIDFILE --m --exec $DAEMON -- $DAEMON_OPTS
	echo "$NAME."
	;;
  *)
	N=/etc/init.d/$NAME
	echo "Usage: $N {start|stop|restart}" >&2
	exit 1
	;;
esac

exit 0


