#! /bin/sh

DAEMON="/usr/bin/python -- /home/kate/ServeToMe/stm.py"
NAME=stm
DESC="ServeToMe daemon"
USER="kate"

set -e

case "$1" in
  start)
	echo -n "Starting $DESC: "
	start-stop-daemon --start --background --chuid $USER --exec $DAEMON
	echo "$NAME."
	;;
  stop)
	echo -n "Stopping $DESC: "
	start-stop-daemon --stop --exec $DAEMON
	echo "$NAME."
	;;
  restart)
	echo -n "Stopping $DESC: "
	start-stop-daemon --stop --exec $DAEMON
	sleep 1
	echo -n "Restarting $DESC: "
	start-stop-daemon --start --background --chuid $USER --exec $DAEMON
	echo "$NAME."
	;;
  *)
	N=/etc/init.d/$NAME
	echo "Usage: $N {start|stop|restart}" >&2
	exit 1
	;;
esac

exit 0


